image: golang:1.16

stages:
  - build
  - deploy

.deployment_script:
  script:
    - mkdir -p ~/.ssh
    - chmod 700 ~/.ssh
    - echo -e "Host *\n\tStrictHostKeyChecking no\n\n" > ~/.ssh/config
    - echo "$SSH_PRIVATE_KEY" > ~/.ssh/id_rsa
    - chmod 600 ~/.ssh/id_rsa
    - echo "Copy build file to $DEST_DIR..."
    - scp -r ./batas-api-deploy $SSH_USER@$SSH_HOST:$DEST_DIR
    - ssh $SSH_USER@$SSH_HOST -C "chmod 755 $DEST_DIR/api-deploy/golang-api-server"
    - ssh $SSH_USER@$SSH_HOST -C "cd $DEST_DIR/api-deploy && ln -s ../storage/api-server/.env ."
    - ssh $SSH_USER@$SSH_HOST -C "cd $DEST_DIR/api-deploy && ln -s ../storage/api-server/logs/ ."
    # Stop and Start service
    - ssh $SSH_USER@$SSH_HOST -C "sudo systemctl stop $SERVICE_FILE"
    - ssh $SSH_USER@$SSH_HOST -C "mv $DEST_DIR/golang-api-server $DEST_DIR/api-server-backup"
    - ssh $SSH_USER@$SSH_HOST -C "mv $DEST_DIR/api-deploy $DEST_DIR/api-server"
    - ssh $SSH_USER@$SSH_HOST -C "sudo systemctl start $SERVICE_FILE"
    # Clean up
    - ssh $SSH_USER@$SSH_HOST -C "rm -rf $DEST_DIR/api-server-backup"

compile:
  stage: build
  allow_failure: false
  only:
    - develop
    - master
  tags:
    - "gitlab-org"
  script:
    - mkdir -p api-deploy/transport/http/gate
    - cp transport/http/gate/*.json api-deploy/transport/http/gate
    - go build -o api-deploy ./...
  artifacts:
    paths:
      - api-deploy

deploy_to_staging:
  stage: deploy
  image: kroniak/ssh-client
  when: on_success
  only:
    - develop
  tags:
    - "gitlab-org"
  variables:
    DEST_DIR: "/apps"
    SERVICE_FILE: "{SERVICE_FILE_NAME}"
    SSH_HOST: "{STAGING_HOST}"
  extends: .deployment_script

deploy_to_production:
  stage: deploy
  image: kroniak/ssh-client
  when: manual
  only:
    - master
  tags:
    - "gitlab-org"
  variables:
    DEST_DIR: "/apps"
    SERVICE_FILE: "{SERVICE_FILE_NAME}"
    SSH_HOST: "{STAGING_HOST}"
  extends: .deployment_script
